CREATE TABLE IF NOT EXISTS memories (
  id TEXT PRIMARY KEY, auth_hash TEXT NOT NULL, revision INTEGER NOT NULL,
  cipher TEXT NOT NULL, updated_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS request_limits (id TEXT PRIMARY KEY, count INTEGER NOT NULL, expires INTEGER NOT NULL);
